### ISSUE TITLE
Ordinal order isn't guaranteed

### ISSUE THREAD

**Issue by TazmanianD** [LMFinney/ts-enums#1]
Unless I'm mistaken, it looks like you are relying on `getOwnPropertyNames` to determine the order of the enum values from which you set the ordinal. I'm pretty sure the order of that array is not guaranteed by the spec and it's possible to get different orderings on different platforms. This could be disastrous if you were using the ordinal on both a web-browser and a server and expecting them to match.

I didn't dig into the code, but the original Enumify library took the list of value names as an array in the `initEnum` function. Perhaps you should do something similar and require the programmer to pass in the values of the enum as an array in the order in which they should be defined. Then the ordinal only changes if the programmer changes it.

At a minimum, you might want to note in your documentation that the ordinal isn't guaranteed between platforms (or who knows, maybe even between separate invocations on the same platform).

**Comment by LMFinney** [comment]
This is an interesting point. I didn't really pay much attention to ordinal (I don't use it in my apps), so it was mostly an afterthought based on it being in Enumify.

I'll take a look.

**Comment by LMFinney** [comment]
Thanks again. I just committed 0.0.6, in which I changed the way the ordinal value is defined. It's now set in the constructor of the instance, and it no longer relies on `getOwnPropertyNames`. 

I chose not to go with Enumify's array-based approach because I prefer having the API have the instances existing as properties directly on the EnumType in the code.

**Comment by TazmanianD** [comment]
Excellent! Thanks for the super-fast turn-around.
